### ISSUE TITLE
[Code] Game Component needs refactor

### ISSUE THREAD

**Issue by Bloodiko** [Bloodiko/sudoku#10]
Game Component Currently uses "useMemo" to force a certain variable to be the same. 
This is not correct, 

It should be used for Performance only. Not to keep a variable identical.

**Comment by Bloodiko** [comment]
Maybe i'll try to use useRef instead, keeping this idea here for the moment.

**Comment by bjesuiter** [comment]
What should useRef do in this szenario?

**Comment by Bloodiko** [comment]
using unsafe "useMemo" which might reset potentially while running, causing the game to be "regenerated" - causing a new game to be created

instead, useRef does not cause rerenders and can hold data dynamically. thus i can create a state where i save that the game has been generated with the current difficulty

**Comment by Bloodiko** [comment]
Fixed in 30578007d6fdf8019c1f04ac896e85ac98b3a131
