### ISSUE TITLE
[Bug] - Crashed by using Numpad

### ISSUE THREAD

**Issue by bjesuiter** [Bloodiko/sudoku#17]
I wanted to input the number 8 via my numpad, and then the app crashed. 
 
 
![Bildschirmfoto 2022-12-10 um 23 58 49](https://user-images.githubusercontent.com/2365676/206878516-0c02d42d-4e01-48d2-b9e8-a2c28715097b.png)

**Comment by bjesuiter** [comment]
This issue seems to not be attached to the numpad anymore, bc normal numbers do also crash in this situation. 

This suggests an error in the state management, that some state gets destroyed in some event.

**Comment by bjesuiter** [comment]
This is the gamestate of my broken game, when you try to enter the 8 in the top-left corner, it crashes
[gamestate.json.zip](https://github.com/Bloodiko/sudoku/files/10201135/gamestate.json.zip)

**Comment by bjesuiter** [comment]
Bug seems to be related to setting a candidate.

**Comment by Bloodiko** [comment]
Issue was Fixed. 

Toggle Candidate in the Reducer converted the CandidateArray to an Object. 
Now Corrected.
