### ISSUE TITLE
[Layout] Ui is broken when width of screen gets to wide

### ISSUE THREAD

**Issue by bjesuiter** [Bloodiko/sudoku#2]
1. Half Screen Width
<img width="1008" alt="Bildschirmfoto 2022-10-02 um 22 28 07" src="https://user-images.githubusercontent.com/2365676/193474921-78103a71-ce14-43a8-b9ec-c02cf0916f37.png">

2. Full Screen Width
<img width="1904" alt="Bildschirmfoto 2022-10-02 um 22 29 43" src="https://user-images.githubusercontent.com/2365676/193474932-f0cb25cd-ac22-48ab-9120-ee0f91d419b6.png">

**Comment by Bloodiko** [comment]
Goal is to have Auto-Adjusting Cell Sizes, based on screen size

This also influences column size, which does "hide" the issue, but doesnt fix it. 

Trying to find a solution. - Need to Experiment with CSS a bit for this.

**Comment by bjesuiter** [comment]
So you want to have bigger cells with bigger screens, possibly with a max-size? (To not have gigantic cells on ultra-wides or 48 inch screens? )

**Comment by bjesuiter** [comment]
I have a small PR which quick-fixes the current state, so that it looks good for now on all screen sizes. 
The new behavior with scaling cells could be added later :)

PR: https://github.com/Bloodiko/sudoku/pull/8
