### ISSUE TITLE
[Mobile] Virtual Keyboard doesn't open 

### ISSUE THREAD

**Issue by bjesuiter** [Bloodiko/sudoku#3]
The Game cannot be played on mobile, bc. the virtual Keyboard doesn't show up.

![IMG_7DA772CDA989-1](https://user-images.githubusercontent.com/2365676/193475031-669c187f-ef7c-4d96-bb2b-2273996246e2.jpeg)

**Comment by Bloodiko** [comment]
[Commit](https://github.com/bloodiko/sudoku/commit/2304e76bdfda83488ddb4408e5d10cf0fb8648e7)

half implemented

Toggle to set candidates in work. (PC Users can use Shift to toggle! )

**Comment by Bloodiko** [comment]
[Toggle Button Commit](https://github.com/Bloodiko/sudoku/commit/4b2391b5f7b544553b388bb305d90ed0460b27c5)

Toggle Button to switch Numpads is now Implemented -> playing on mobile now possible
